version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/storage
      - /var/www/html/bootstrap/cache
      - ./nginx.conf:/etc/nginx/sites-available/default
      - ./startup.sh:/startup.sh
      - ./index.php:/var/www/html/index.php
      - ./storage/logs:/var/www/html/storage/logs
    ports:
      - "8000:80"
      - "9003:9003" # Xdebug port
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: your_laravel_db_password
      # DEBUG
      APP_ENV: local
      APP_DEBUG: "true"
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: your_laravel_db_password
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    volumes:
      - dbdata:/var/lib/mysql
    command: mysqld --slow_query_log=1 --slow_query_log_file=/dev/stdout --long_query_time=2

volumes:
  dbdata:
