name: Docker Test

on:
  push:
    branches:
      - "**" # This will run the action on pushes to any branch

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and start Docker containers
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Check Docker containers and wait for application
        run: |
          echo "Checking Docker containers..."
          docker-compose -f docker-compose.yml ps

          echo "Checking logs of the app container..."
          docker-compose -f docker-compose.yml logs app

          echo "Waiting for application to be ready..."
          attempt_counter=0
          max_attempts=3

          until curl -sSf -o /dev/null http://localhost:8000
          do
              if [ ${attempt_counter} -eq ${max_attempts} ]; then
                echo "Max attempts (${max_attempts}) reached. Application failed to start."
                echo "Final attempt output:"
                curl -v http://localhost:8000
                echo "Docker logs:"
                docker-compose -f docker-compose.yml logs
                exit 1
              fi
              
              echo "Attempt ${attempt_counter}/${max_attempts} failed. Retrying in 2 seconds..."
              attempt_counter=$((attempt_counter+1))
              sleep 2
          done

          echo "Application is up and running!"

      # - name: Run Laravel migrations
      #   run: docker-compose -f docker-compose.yml exec -T app php artisan migrate

      # # Node.js end-to-end tests would go here
      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "14"

      # - name: Install Node.js dependencies
      #   run: |
      #     # Navigate to your Node.js project directory if it's different
      #     # cd path/to/nodejs/project
      #     npm install

      # - name: Run end-to-end tests
      #   run: |
      #     # This is a placeholder. Replace with your actual end-to-end test command
      #     echo "Running end-to-end tests..."
      #     # npm run test:e2e

      - name: Stop Docker containers
        run: docker-compose -f docker-compose.yml down

      - name: Test completed successfully
        run: echo "Test completed successfully"
