name: Docker Test and Push

on:
  push:
    branches:
      - "**" # This will run the action on pushes to any branch

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and start Docker containers
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Check Docker containers health status
        run: |
          echo "Waiting for application to be ready..."
          until [ "$(docker inspect --format='{{json .State.Health.Status}}' your-container-name)" == "\"healthy\"" ]; do
            sleep 5;
            echo "Waiting for the application to be healthy..."
          done

      # - name: Check Docker containers and wait for application
      #   run: |
      #     echo "Checking Docker containers..."
      #     docker-compose -f docker-compose.yml ps

      #     echo "Checking logs of the app container..."
      #     docker-compose -f docker-compose.yml logs app

      #     echo "Waiting for application to be ready..."
      #     attempt_counter=0
      #     max_attempts=3

      #     until curl -sSf -o /dev/null http://localhost:8000
      #     do
      #         if [ ${attempt_counter} -eq ${max_attempts} ]; then
      #           echo "Max attempts (${max_attempts}) reached. Application failed to start."
      #           echo "Final attempt output:"
      #           curl -v http://localhost:8000
      #           echo "Docker logs:"
      #           docker-compose -f docker-compose.yml logs
      #           exit 1
      #         fi
              
      #         echo "Attempt ${attempt_counter}/${max_attempts} failed. Retrying in 2 seconds..."
      #         attempt_counter=$((attempt_counter+1))
      #         sleep 2
      #     done

          echo "Application is up and running!"

      - name: Stop Docker containers
        run: docker-compose -f docker-compose.yml down

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker tag your-image-name:latest ghcr.io/${{ github.repository }}/your-image-name:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/your-image-name:${{ github.sha }}

      - name: Test completed successfully
        run: echo "Test completed successfully"
